[build]
  command = "bun install && NODE_OPTIONS='--max-old-space-size=4096' bun run build"
  functions = ".netlify/functions"

[build.environment]
  DISABLE_ESLINT_PLUGIN = "true"
  SKIP_ENV_VALIDATION = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  SKIP_SITEMAP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
