[build]
  command = "bun install && NODE_OPTIONS='--max-old-space-size=4096' bun run build:netlify"
  functions = ".netlify/functions"

[build.environment]
  DISABLE_ESLINT_PLUGIN = "true"
  SKIP_ENV_VALIDATION = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  SKIP_SITEMAP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["sharp"]

[build.processing]
  skip_processing = false

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
