[build]
  command = "NODE_OPTIONS='--max-old-space-size=8192' SKIP_ENV_VALIDATION=true DISABLE_ESLINT_PLUGIN=true bun run build"
  functions = ".netlify/functions"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ./netlify.toml"

[build.environment]
  DISABLE_ESLINT_PLUGIN = "true"
  SKIP_ENV_VALIDATION = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_BUN = "true"
  # Supabase environment variables properly configured
  NEXT_PUBLIC_SUPABASE_URL = "https://isjnwsuodldqrcntheoh.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlzam53c3VvZGxkcXJjbnRoZW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTcyNDUsImV4cCI6MjA3MTc3MzI0NX0.v-5CbRjEaiuVrO5YHnpJ1giRY85Ovg8QTxaE2DOInFc"
  SUPABASE_SERVICE_ROLE_KEY = "placeholder_service_role_key_for_build_only"
  ENCRYPTION_KEY = "YvPJrFGmL9qHS2xTb5D8A3X7wWgkC6Nz"
  # Contentful environment variables
  CONTENTFUL_SPACE_ID = "4x22ux8m6s1o"
  CONTENTFUL_ENVIRONMENT = "master"
  CONTENTFUL_USE_PREVIEW = "false"
  CONTENTFUL_SERVICE_TYPE_ID = "serviceDataserviceData"
  CONTENTFUL_LOCATION_TYPE_ID = "locationData"
  CONTENTFUL_BLOG_TEMPLATE_TYPE_ID = "blogTemplate"
  CONTENTFUL_BLOG_POST_TYPE_ID = "pageBlogPost"
  GENERATION_MODE = "fallback"
  USE_MOCK_DATA = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["sharp", "contentful"]
  node_bundler = "esbuild"

[functions.options]
  timeout = 30

[dev]
  framework = "next"
  autoLaunch = false

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = false

[build.processing.images]
  compress = false

[[edge_functions]]
  path = "/"
  function = "ab-testing"